### PR TITLE
Freeze pip, setuptools, and virtualenv

### LINKED ISSUE #2714: 'pycrypto' error when installing fullstack
I'm following the instructions to installing named-release/dogwood.rc fullstack on amazon, with the following steps:
- provision instance on EC2
- ssh in
- sudo apt-get update -y
- sudo apt-get upgrade -y
- sudo reboot
- ssh in
- export OPENEDX_RELEASE="named-release/dogwood.rc"
- sudo wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo bash
- sudo wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

The last step fails with the following trace from ansible:

`...
Found existing installation: pycrypto 2.4.1
Detected a distutils installed project ('pycrypto') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
sudo: ansible-playbook: command not found
`

### PR DESCRIPTION
**Pull request by arbrandes**
Pip 8.0.0, released a few hours ago, tries to uninstall deb-installed
python modules that it wants to upgrade, and always fails when doing so.
The effect is that configuration/requirements.txt cannot be fulfilled,
notably ansible 1.9.3-edx, which requires an upgrade to pycrypto.

This forces the installation of pip to the latest one prior to 8.0.0,
7.1.2.

It also freezes setuptools and virtualenv, so that they should all match
the current versions required on
playbooks/roles/common_vars/defaults/main.yml:common_pip_pkgs.

Fixes #2714

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @arbrandes! I've created [OSPR-1078](https://openedx.atlassian.net/browse/OSPR-1078) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     You haven't added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo. Please create a new pull request to do so!     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@arbrandes Thanks! I wondered if we'd see some fallout from pip 8.  Maybe we should pin the version of setuptools while we're at it. @edx/devops Thoughts?

Send in the contributors agreement, and we can get this merged.

**Comment by fredsmith** [comment]
@nedbat we should freeze both pip and setuptools until we've had a chance to test them properly.

**Comment by arbrandes** [comment]
@nedbat, I've just sent the signed contributor's agreement.

Should I update this PR with a pinned setuptools?  The automatically-installed version that is (at least seems to be) working on my latest installation from master is 19.4.

**Comment by nedbat** [comment]
@arbrandes yes, please pin all of the pip-installed packages.  And I guess there's no need for `--upgrade` once the versions are pinned.

**Comment by nedbat** [comment]
@arbrandes we've received your contributor agreement, thanks.

**Comment by arbrandes** [comment]
@nedbat, I've updated the PR according to your comments.

File: util/install/sandbox.sh [hunk 1]
```diff
@@ -32,9 +32,9 @@ sudo apt-get upgrade -y
 ## Install system pre-requisites
 ##
 sudo apt-get install -y build-essential software-properties-common curl git-core libxml2-dev libxslt1-dev python-pip libmysqlclient-dev python-apt python-dev libxmlsec1-dev libfreetype6-dev swig gcc-4.8 g++-4.8
-sudo pip install --upgrade pip
-sudo pip install --upgrade setuptools
-sudo -H pip install --upgrade virtualenv
+sudo pip install --upgrade pip==7.1.2
+sudo pip install --upgrade setuptools==18.3.2
```
Comment (nedbat) [inline util/install/sandbox.sh:36]: I'm wondering how you chose this version. it isn't the latest/

Comment (arbrandes) [inline util/install/sandbox.sh:36]: @nedbat, a fair question. :)  I based myself on what the configuration repo is already installing.  See https://github.com/edx/configuration/blob/master/playbooks/roles/common_vars/defaults/main.yml#L105.  It felt like keeping things in sync with that would be a good idea.

Comment (arbrandes) [inline util/install/sandbox.sh:36]: PS: the ansible variable referenced above is used to install the referenced packages via the "common" role, which as a dependency of "edxapp", gets installed anywhere ansible is likely to be run.  Hence, the idea of keeping them in sync.

**Comment by e0d** [comment]
@arbrandes can you add to util/ansible-bootstrap.sh as well?  Other than that, I'm happy with this

**Comment by fredsmith** [comment]
LGTM :+1:  @e0d @feanil second thumb?

**Comment by feanil** [comment]
:+1:  after `util/ansible-bootstrap.sh` has been updated.

**Comment by arbrandes** [comment]
Thanks @e0d, @feanil, and @fredsmith!  PR updated, addressing the above comments.
